name: Build Web

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
#      - run: flutter pub get
#      - run: flutter build web --dart-define TOMTOM_KEY=$SECRETS_FILE_CONTENTS
      - uses: erickzanardo/flutter-gh-pages@v7
        with:
          customArgs: --dart-define TOMTOM_KEY=${{ secrets.SECRETS_FILE_CONTENTS }}
          basehref: /namma_bengaluru_metro/